### ISSUE TITLE
大兄弟.麻烦帮忙看一下这个问题.也是有关于自定义cli3模板的

### ISSUE THREAD

**Issue by ranwawa** [zoux/vue-cli-plugin-template#1]
https://segmentfault.com/q/1010000018084330

感谢.

**Comment by zoux** [comment]
不好意思，现在才关注到你提的问题。看了你帖子里的内容，很高兴你的问题已经有了解决方案～

我觉得利用 ide 本身的 template 功能很棒，不过如果你觉得这种方式缺乏一定的灵活性和交互性的话，
个人建议你可以尝试：

1. 重一点可以基于 vue-cli 的原理拉取线上模版 + 注入变量的方式生成代码；
2. 轻一点简单写个 node 脚本直接 copy 指定目录下的模版文件。

这两种方式在我和同事的实际生产中都有应用，和你一样都是为了解决重复工作。

希望以上拙见对你有所帮助哈～
